### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by vladshoob** [JackNoordhuis/laravel-database-hashing#2]
Please add 5.8.* support to composer.json, it seems like it is still compatible. But tests should be run.

**Comment by JackNoordhuis** [comment]
Resolved by 45193ad067300291f5fdfd80405620ced731b2b9. Tested changes locally with a test project.

**Comment by vladshoob** [comment]
> Resolved by [45193ad](https://github.com/JackNoordhuis/laravel-database-hashing/commit/45193ad067300291f5fdfd80405620ced731b2b9). Tested changes locally with a test project.

Thanks for update. My app heavily using this feature due to the security of personal data of EU citizens.

But it is strange, the change did not pick up by composer installer yet.

**Comment by JackNoordhuis** [comment]
I've just tagged a new release with Laravel 5.8 support so composer should now detect the changes.
